name: Portfolio Tracker Daily Report

on:
  schedule:
    # Run daily at 9:00 PM IST (15:30 UTC)
    - cron: '30 15 * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  portfolio-tracker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@master
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run portfolio tracker
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
        RECIPIENT_IDS: ${{ secrets.RECIPIENT_IDS }}
        PMS_USERNAME: ${{ secrets.PMS_USERNAME }}
        PMS_PWD: ${{ secrets.PMS_PWD }}
        LOGIN_URL: ${{ secrets.LOGIN_URL }}
        SESSION_API_URL: ${{ secrets.SESSION_API_URL }}
        INVESTOR_API_URL: ${{ secrets.INVESTOR_API_URL }}
      run: |
        python portfolio_tracker.py
    
    - name: Commit and push portfolio data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add portfolio_data.json
        git diff --staged --quiet || git commit -m "📊 Update portfolio data - $(date '+%Y-%m-%d %H:%M:%S UTC')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: debug-logs
        path: |
          *.log
          *.png
        retention-days: 7